manifest:
  remotes:
    - name: tfm
      url-base: https://git.trustedfirmware.org/TF-M
    - name: armmbed
      url-base: https://github.com/ARMmbed
    - name: mcutools
      url-base: https://github.com/mcu-tools
    - name: armsw
      url-base: https://github.com/ARM-software/
  projects:
    - name: trusted-firmware-m
      remote: tfm
      revision: TF-Mv1.4.0-RC3
    - name: psa-arch-tests
      remote: armsw
      revision: 51ff2bd
    - name: tf-m-tests
      remote: tfm
      revision: 26b2d78
    - name: mbedtls
      remote: armmbed
      revision: mbedtls-3.0.0
      # Post checkout commands
      # make generated_files
      # git apply ../trusted-firmware-m/lib/ext/mbedcrypto/*.patch
    - name: mcuboot
      remote: mcutools
      revision: TF-Mv1.4-integ

  self:
    path: tfm-manifest
